// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace BookApp.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231124132922_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lobortis scelerisque fermentum dui faucibus. In hac habitasse platea dictumst quisque sagittis purus sit. At lectus urna duis convallis convallis tellus id interdum. Mauris vitae ultricies leo integer malesuada nunc. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Ultrices gravida dictum fusce ut placerat orci nulla. Interdum velit euismod in pellentesque massa placerat. Quam viverra orci sagittis eu volutpat odio facilisis mauris sit. Consequat id porta nibh venenatis cras sed. Malesuada fames ac turpis egestas. Eget dolor morbi non arcu risus quis varius quam quisque. Volutpat ac tincidunt vitae semper. Eu mi bibendum neque egestas congue quisque egestas. Ultrices tincidunt arcu non sodales. Id ornare arcu odio ut sem nulla pharetra diam sit.",
                            Title = "Title"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
